name: build

on: 
  push:
    paths: 
      - build/**
      - .github/workflows/build.yml

jobs:
    osx:
        runs-on: macos-13
    
        steps:
               - uses: actions/checkout@v2
               - name: Build
                 run: |
                    ./build_osx.sh
               - name: Upload
                 uses: actions/upload-artifact@v4
                 with:
                    path: ./Plugins/tolua.bundle/**/*
                    name: tolua
                    compression-level: 0