name: build

on: 
  push:
    paths: 
      - ./*.sh
      - .github/workflows/build.yml

jobs:
    osx:
        runs-on: macos-13
    
        steps:
                - uses: actions/checkout@v4
                - name: Build
                  run: |
                      ./build_osx.sh
                - name: Upload
                  uses: actions/upload-artifact@v4
                  with:
                    path: ./Plugins/**/*
                    name: tolua-osx
                    compression-level: 0
        
    
    ios:
        runs-on: macos-13
    
        steps:
                - uses: actions/checkout@v4
                - name: Build
                  run: |
                    ./build_ios.sh
                - name: Upload
                  uses: actions/upload-artifact@v4
                  with:
                    path: ./Plugins/**/*
                    name: tolua-ios
                    compression-level: 0
    
    window:
        runs-on: windows-latest

        defaults:
            run:
                shell: bash
    
        steps:
                - uses: actions/checkout@v4
                - name: Build
                  run: |
                    # ./build_win32.sh
                    ./build_win64.sh
                - name: Upload
                  uses: actions/upload-artifact@v4
                  with:
                    path: ./Plugins/**/*
                    name: tolua-win
                    compression-level: 0
  
    linux:
        runs-on: ubuntu-latest
    
        steps:
                - uses: actions/checkout@v4
                - name: Build
                  run: |
                    # ./build_win32.sh
                    ./build_ubuntu.sh
                - name: Upload
                  uses: actions/upload-artifact@v4
                  with:
                    path: ./Plugins/**/*
                    name: tolua-linux
                    compression-level: 0

    android:
        runs-on: ubuntu-latest
    
        steps:
                - uses: actions/checkout@v4
                - name: Install NDK r15c
                  run: |
                    wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
                    sudo apt install unzip -y
                    unzip -q NDK
                    sudo apt-get install libncurses5
                - name: Build arm64
                  run: |
                    export ANDROID_NDK_HOME=$(pwd)/android-ndk-r15c
                    chmod 777 ./build_arm64.sh
                    ./build_arm64.sh
                - name: Install NDK r10e
                  run: |
                    wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip
                    sudo apt install unzip -y
                    unzip -q NDK
                    # sudo apt-get install libncurses5:i386
                    sudo apt-get install gcc-multilib
                - name: Build arm
                  run: |
                    export ANDROID_NDK_HOME=$(pwd)/android-ndk-r10e
                    chmod 777 ./build_arm.sh
                    ./build_arm.sh
                - name: Upload
                  uses: actions/upload-artifact@v4
                  with:
                    path: ./Plugins/**/*
                    name: tolua-android
                    compression-level: 0